language: erlang
env:
  matrix:
  - ST=GemStone-3.2.0
addons:
  firefox: "23.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - export PROJECT_HOME="$(pwd)"
  - cd $HOME
  - wget -q -O builderCI.zip https://github.com/SWTI2014/builderCI/zipball/master
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.32.0.jar
  - unzip -q builderCI.zip
  - cd SWTI2014-builderCI*
  - source build_env_vars
  - ln -s $PROJECT_HOME $GIT_PATH
  - "./build_image.sh"

before_script:
  - java -jar $HOME/selenium-server-standalone-2.32.0.jar -browserSessionReuse &
  - sleep 5
  - sudo netstat -tulp

# use a different script if you want to customize how travis tests are run
# use verbose flag to dump transcript unconditionally
script: $BUILDER_CI_HOME/testTravisCI.sh -verbose
script:
  - "$BUILDER_CI_HOME/testTravisCI.sh -verbose"
