language: erlang
env:
  matrix:
  - ST=Pharo-2.0
  global:
  - secure: mRX49i/sLNJc7U8SlA3wKFc64BA0ejcLmN7Rn0PWtOlpzLCf33yXVTabL/z4dJU3nCNC1STWJWJVVDhEHk68sHbTbmX1tDrarSlq+lyNIAAnQC5lX5IR86XObMGnFwildcRU8KFZOYP6hkWnWwMyKK3JN2Sl8rjjYX18OYCEDmc=
  - secure: auhH1BX2uUlFK6NT3dl4Ad4UEVLKiJSGOk0XohYhGokzvVExaqC02eLQ/ixMpuZCKmcA7qq7Ew7Svj8IZfbWbF5cWV3ycVPciSy2DTdGh2r2cT9JHtozOFML6sbwMAiqkvPKeiwvrlMZpDVq0wBC5iQ83zqhngCqmHS5AC8fjvM=
addons:
  sauce_connect: true
before_install:
- sudo apt-get -qq install libssl0.9.8:i386
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get purge firefox
- sudo apt-get -qq update
- sudo wget ftp://ftp.mozilla.org/pub/firefox/releases/23.0.1/linux-x86_64/en-GB/firefox-23.0.1.tar.bz2
- sudo tar xjf firefox-23.0.1.tar.bz2
- sudo ln -s firefox/firefox /usr/bin/firefox
- sudo netstat -tulp
install:
- export PROJECT_HOME="$(pwd)"
- cd $HOME
#- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.32.0.jar
- wget -q -O builderCI.zip https://github.com/SWTI2014/builderCI/zipball/master
- unzip -q builderCI.zip
- cd SWTI2014-builderCI*
- source build_env_vars
- ln -s $PROJECT_HOME $GIT_PATH
- "./build_image.sh"
#before_script:
#- java -jar $HOME/selenium-server-standalone-2.32.0.jar &
#- sleep 5
script: "$BUILDER_CI_HOME/testTravisCI.sh"
