language: erlang

# Choose which platforms you want your builds run against (done in parallel)
env:
   - ST=Pharo-3.0

# For SqueakSSL
before_install:
   - sudo apt-get -qq install libssl0.9.8:i386before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start

# Boilerplate ... should be no reason to edit the install section
install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
#   - pip install selenium nose --use-mirrors
   - wget -q -O builderCI.zip https://github.com/SWTI2014/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd SWTI2014-builderCI*
   - source build_env_var
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh
   
before_script:
   - java -jar $HOME/selenium-server-standalone-2.42.2.jar &

# use a different script if you want to customize how travis tests are run
# use verbose flag to dump transcript unconditionally
script: $BUILDER_CI_HOME/testTravisCI.sh # -verbose 
